---
- name: installing ec2
  hosts: localhost
  become: true
  tasks:
  - name: create a cloudformation stack
    cloudformation:
      stack_name: "ansible-cloudformation"
      state: "present"
      region: "ap-south-1"
      disable_rollback: true
      template_url: https://ansible-chandra.s3.ap-south-1.amazonaws.com/ec2.yaml
      tags:
        Stack: "ansible-cloudformation"

